name: CI

on:
  push:
    branches: [main, feature.*]
    tags: ['[0-9]+.[0-9]+.*']
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  double_check:
    name: Double-check
    runs-on: ubuntu-latest
    needs: [test]
    if: "startsWith(github.ref, 'refs/tags/')"

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/util/initialize
        with: {github-token: "${{ github.token }}"}

      - name: Run checks
        run: dart run grinder double-check-before-release

  test_vendor:
    needs: [double_check]
    if: "startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/test-vendor.yml
    secrets: inherit

  release:
    needs: [test_vendor]
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
