name: Release

on:
  workflow_call:

jobs:
  build_android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  build_linux:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  build_linux_musl:
    uses: ./.github/workflows/build-linux-musl.yml
    secrets: inherit

  build_macos:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build_windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  release_github:
    name: Release Github
    runs-on: ubuntu-latest
    needs: [build_android, build_linux, build_linux_musl, build_macos, build_windows]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/util/initialize
        with: {github-token: "${{ github.token }}"}

      - name: Deploy
        run: dart run grinder pkg-github-release
        env:
          GH_TOKEN: "${{ github.token }}"
          GH_USER: "${{ github.actor }}"

  deploy_github:
    name: Deploy Github
    runs-on: ubuntu-latest
    needs: [release_github]

    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build-*/*
